# Git Abbreviations
abbr -a ga  'git add'
abbr -a gc  'git commit'
abbr -a gcm 'git commit -m'
abbr -a gp  'git push'
abbr -a gpl 'git pull'
abbr -a gs  'git status'
abbr -a gd  'git diff'
abbr -a gco 'git checkout'
abbr -a gb  'git branch'
abbr -a gl  'git log --oneline --graph --decorate'
